// <auto-generated />
using System;
using ASM2C5API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASM2C5API.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    [Migration("20240611160753_Caphe")]
    partial class Caphe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASM2C5API.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("ASM2C5API.Models.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("ASM2C5API.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdND")
                        .HasColumnType("int");

                    b.Property<int>("MaChiTietHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("IdND");

                    b.HasIndex("MaChiTietHoaDon");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("ASM2C5API.Models.SanPham", b =>
                {
                    b.Property<int>("IdSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Gia")
                        .HasColumnType("real");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaChiTietHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSP");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("MaChiTietHoaDon");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("ASM2C5API.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TenDN")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdND");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("ASM2C5API.Models.VaiTro", b =>
                {
                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDN")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Role");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("ASM2C5API.Models.HoaDon", b =>
                {
                    b.HasOne("ASM2C5API.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM2C5API.Models.ChiTietHoaDon", "ChiTietHoaDon")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaChiTietHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ASM2C5API.Models.SanPham", b =>
                {
                    b.HasOne("ASM2C5API.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPham")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM2C5API.Models.ChiTietHoaDon", "ChiTietHoaDon")
                        .WithMany("SanPham")
                        .HasForeignKey("MaChiTietHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ASM2C5API.Models.TaiKhoan", b =>
                {
                    b.HasOne("ASM2C5API.Models.VaiTro", "VaiTro")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("ASM2C5API.Models.TaiKhoan", "Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("ASM2C5API.Models.ChiTietHoaDon", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM2C5API.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM2C5API.Models.TaiKhoan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("ASM2C5API.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
